version: '3'

networks:
  docker-net:
    driver: bridge

services:
  postgres:
    image: kartoza/postgis:12.0
    container_name: postgres
    #restart: always
    environment:
      - POSTGRES_USER=yellowpepper
      - POSTGRES_PASS=yellowpepper
      - POSTGRES_DBNAME=yellowpepper
      #- POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "yellowpepper", "-P", "yellowpepper" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres-data:/var/lib/postgresql/12
    ports:
      - "5432:5432"
    networks:
      - docker-net

  pgadmin4:
    image: dpage/pgadmin4:4.25
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@test.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - 15432:80
    networks:
      - docker-net
