-- customer
INSERT INTO PUBLIC.CUSTOMER
(FIRST_NAME, SECOND_NAME, SURNAME, SECOND_SURNAME)
VALUES('Jorge', 'Ulises', 'Useche', 'Cuellar');

INSERT INTO PUBLIC.CUSTOMER
(FIRST_NAME, SECOND_NAME, SURNAME, SECOND_SURNAME)
VALUES('John', '', 'Doe', '');

INSERT INTO PUBLIC.CUSTOMER
(FIRST_NAME, SECOND_NAME, SURNAME, SECOND_SURNAME)
VALUES('Jane', '', 'Doe', '');

INSERT INTO PUBLIC.CUSTOMER
(FIRST_NAME, SECOND_NAME, SURNAME, SECOND_SURNAME)
VALUES('Simón', 'José Antonio de la Santísima Trinidad', 'Bolívar', 'y Ponte Palacios y Blanco');

INSERT INTO PUBLIC.CUSTOMER
(FIRST_NAME, SECOND_NAME, SURNAME, SECOND_SURNAME)
VALUES('Jonny', '', 'Deep', '');

-- currency
INSERT INTO PUBLIC.CURRENCY
(SYMBOL, ABBREVIATION)
VALUES('$', 'USD');

INSERT INTO PUBLIC.CURRENCY
(SYMBOL, ABBREVIATION)
VALUES('$', 'CAD');

INSERT INTO PUBLIC.CURRENCY
(SYMBOL, ABBREVIATION)
VALUES('$', 'COP');

INSERT INTO PUBLIC.CURRENCY
(SYMBOL, ABBREVIATION)
VALUES('€', 'EUR');

INSERT INTO PUBLIC.CURRENCY
(SYMBOL, ABBREVIATION)
VALUES('R$', 'BRL');

-- account
INSERT INTO PUBLIC.ACCOUNT
(ID_HOLDER, AMOUNT, ID_CURRENCY)
VALUES(1, 1000, 1); -- 1th account

INSERT INTO PUBLIC.ACCOUNT
(ID_HOLDER, AMOUNT, ID_CURRENCY)
VALUES(1, 0, 2); -- 2th account

INSERT INTO PUBLIC.ACCOUNT
(ID_HOLDER, AMOUNT, ID_CURRENCY)
VALUES(2, 2000, 2); -- 3th account

INSERT INTO PUBLIC.ACCOUNT
(ID_HOLDER, AMOUNT, ID_CURRENCY)
VALUES(3, 0, 1); -- 4th account

INSERT INTO PUBLIC.ACCOUNT
(ID_HOLDER, AMOUNT, ID_CURRENCY)
VALUES(4, 1500.5, 2); -- 5th account

INSERT INTO PUBLIC.ACCOUNT
(ID_HOLDER, AMOUNT, ID_CURRENCY)
VALUES(5, 12.5, 2); -- 6th account

INSERT INTO PUBLIC.ACCOUNT
(ID_HOLDER, AMOUNT, ID_CURRENCY)
VALUES(4, 10.99, 1); -- 7th account

INSERT INTO PUBLIC.ACCOUNT
(ID_HOLDER, AMOUNT, ID_CURRENCY)
VALUES(5, 0.5, 1); -- 8th account

-- for testing amounts before transfer
-- case USD USD
INSERT INTO PUBLIC.ACCOUNT
(ID_HOLDER, AMOUNT, ID_CURRENCY)
VALUES(1, 1.002, 1); -- 9th account

INSERT INTO PUBLIC.ACCOUNT
(ID_HOLDER, AMOUNT, ID_CURRENCY)
VALUES(2, 0, 1); -- 10th account

-- case CAD USD
INSERT INTO PUBLIC.ACCOUNT
(ID_HOLDER, AMOUNT, ID_CURRENCY)
VALUES(1, 1.26252, 2); -- 11th account

INSERT INTO PUBLIC.ACCOUNT
(ID_HOLDER, AMOUNT, ID_CURRENCY)
VALUES(2, 0, 1); -- 12th account

-- case USD CAD
INSERT INTO PUBLIC.ACCOUNT
(ID_HOLDER, AMOUNT, ID_CURRENCY)
VALUES(1, 1.002, 1); -- 13th account

INSERT INTO PUBLIC.ACCOUNT
(ID_HOLDER, AMOUNT, ID_CURRENCY)
VALUES(2, 0, 2); -- 14th account

-- case CAD CAD
INSERT INTO PUBLIC.ACCOUNT
(ID_HOLDER, AMOUNT, ID_CURRENCY)
VALUES(1, 1.26252, 2); -- 15th account

INSERT INTO PUBLIC.ACCOUNT
(ID_HOLDER, AMOUNT, ID_CURRENCY)
VALUES(2, 0, 2); -- 16th account

-- transfer
