import  com.yellowpepper.challenge.domain.AccountTransferValidationRequest;

rule "account without funds"
    when
        validationObject : AccountTransferValidationRequest( accountAmount < amountToTransfer * (1+tax) );
    then
        validationObject.setAvailability("NO_FUNDS");
end;

rule "account limits"
    when
        validationObject : AccountTransferValidationRequest( timesAccountTransaction >= 3 );
    then
        validationObject.setAvailability("LIMITS_EXCEED");
end;

